const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const canvas=$('#canvas'),wrap=$('#canvasWrap'),workspace=$('#workspace'),toast=$('#toast'),connectionLayer=$('#connectionLayer');
let zoom=.72,panX=10,panY=0,tool='select',selected=new Set(),panState=null,dragState=null,boxState=null,connectStart=null,pendingImagePoint=null,idSeed=30;
let undoStack=[],redoStack=[],clipboard=[];
let spaceDown=false,activity=[],pendingAiSelection=[];

function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.remove('show'),2200)}
function transform(){canvas.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;$('#zoomValue').textContent=`${Math.round(zoom*100)}%`}
function canvasPoint(e){const r=wrap.getBoundingClientRect();return{x:(e.clientX-r.left-panX)/zoom,y:(e.clientY-r.top-panY)/zoom}}
function select(el,add=false){if(!add)clearSelection();if(!el?.dataset.id)return;selected.add(el.dataset.id);el.classList.add('selected');updateSelectionBar()}
function clearSelection(){selected.clear();$$('.object.selected').forEach(el=>el.classList.remove('selected'));updateSelectionBar()}
function logActivity(type,detail){activity.unshift({type,detail,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});activity=activity.slice(0,40);renderActivity()}
function renderActivity(){const list=$('#activityList');if(!list)return;list.innerHTML=activity.length?activity.map(item=>`<article><i>${item.type.slice(0,1)}</i><div><strong>${item.type}</strong><p>${item.detail}</p><time>${item.time}</time></div></article>`).join(''):'<div class="activity-empty">Canvas actions will be recorded here.</div>'}
function updateSelectionBar(){const n=selected.size,bar=$('#selectionActions');$('#selectedCount').textContent=n;bar.classList.toggle('hidden',n<1);if(!n)return;const items=[...selected].map(id=>$(`[data-id="${id}"]`)).filter(Boolean),r=wrap.getBoundingClientRect(),left=Math.max(...items.map(el=>el.getBoundingClientRect().right))-r.left+12,top=Math.min(...items.map(el=>el.getBoundingClientRect().top))-r.top;bar.style.left=`${Math.min(left,wrap.clientWidth-bar.offsetWidth-12)}px`;bar.style.top=`${Math.max(12,top)}px`;bar.style.transform='none'}
function snapshot(){return $$('.object').map(el=>el.outerHTML)}
function saveHistory(){undoStack.push(snapshot());if(undoStack.length>30)undoStack.shift();redoStack=[];updateHistoryButtons()}
function restore(state){$$('.object').forEach(el=>el.remove());canvas.insertAdjacentHTML('beforeend',state.join(''));$$('.object').forEach(bindObject);clearSelection();renderConnections()}
function undo(){if(!undoStack.length)return;redoStack.push(snapshot());restore(undoStack.pop());updateHistoryButtons();notify('Undone');logActivity('Undo','Reverted the last canvas change')}
function redo(){if(!redoStack.length)return;undoStack.push(snapshot());restore(redoStack.pop());updateHistoryButtons();notify('Redone');logActivity('Redo','Restored the reverted canvas change')}
function updateHistoryButtons(){$('#undoBtn').disabled=!undoStack.length;$('#redoBtn').disabled=!redoStack.length}
function createObject(type,x,y,extra={}){saveHistory();const id=`o${idSeed++}`;let el=document.createElement(type==='text'?'div':'article');el.dataset.id=id;el.dataset.type=type;el.className=`object created ${type==='sticky'?'sticky '+(extra.color||'coral'):type==='text'?'text-block':'image-card'}`;el.style.left=`${x}px`;el.style.top=`${y}px`;
  if(type==='sticky')el.innerHTML='<p contenteditable="true">Write a thought...</p><footer><span>You</span><button class="note-vote">♡ <b>0</b></button></footer>';
  if(type==='text')el.innerHTML='<p contenteditable="true">Type something meaningful</p>';
  if(type==='image')el.innerHTML=`<img src="${extra.src}" alt="Uploaded canvas reference"><footer>Reference image</footer>`;
  canvas.append(el);bindObject(el);select(el);logActivity('Note created',`${type} added to the page`);setTimeout(()=>el.querySelector('[contenteditable]')?.focus(),20);return el}
function bindObject(el){el.addEventListener('pointerdown',objectDown);el.querySelector('.note-vote')?.addEventListener('click',voteClick);el.addEventListener('dblclick',()=>el.querySelector('[contenteditable]')?.focus());if(el.dataset.type==='comment')el.addEventListener('click',e=>{if(!e.target.closest('button,[contenteditable]'))el.classList.toggle('open')})}
function objectDown(e){const el=e.currentTarget;if(e.button===1||spaceDown){e.preventDefault();e.stopPropagation();panState={x:e.clientX-panX,y:e.clientY-panY};canvas.classList.add('panning');return}if(e.target.closest('[contenteditable],button'))return;
  if(tool==='vote'){e.preventDefault();voteElement(el);return}
  if(tool==='comment'){e.preventDefault();addComment(el);return}
  if(tool==='connect'){e.preventDefault();handleConnect(el);return}
  if(tool!=='select')return;
  e.stopPropagation();if(!selected.has(el.dataset.id))select(el,e.shiftKey);saveHistory();const p=canvasPoint(e);const targets=[...selected].map(id=>$(`[data-id="${id}"]`)).filter(Boolean);dragState={p,targets,positions:targets.map(t=>({x:parseFloat(t.style.left)||0,y:parseFloat(t.style.top)||0}))};el.setPointerCapture(e.pointerId)}
function canvasDown(e){if(e.target!==canvas&&e.target!==connectionLayer)return;const p=canvasPoint(e);
  if(e.button===1||spaceDown){e.preventDefault();panState={x:e.clientX-panX,y:e.clientY-panY};canvas.classList.add('panning');return}
  if(tool==='sticky'){createObject('sticky',p.x-85,p.y-60,{color:['yellow','green','blue','coral'][idSeed%4]});notify('Sticky note added');return}
  if(tool==='text'){createObject('text',p.x,p.y);notify('Text block added');return}
  if(tool==='image'){pendingImagePoint=p;$('#imageInput').click();return}
  if(tool==='comment'){createComment(p.x,p.y);return}
  if(tool==='hand'){panState={x:e.clientX-panX,y:e.clientY-panY};canvas.classList.add('panning');return}
  if(tool==='ai'){notify('Select objects first, then use AI Organise');return}
  if(tool==='select'){clearSelection();boxState={start:p,ai:false};const box=$('#selectionBox');box.classList.remove('ai-box');box.style.cssText=`display:block;left:${p.x}px;top:${p.y}px;width:0;height:0`}}
function pointerMove(e){if(panState){panX=e.clientX-panState.x;panY=e.clientY-panState.y;transform()}
  if(dragState){const p=canvasPoint(e),dx=p.x-dragState.p.x,dy=p.y-dragState.p.y;dragState.targets.forEach((t,i)=>{t.style.left=`${dragState.positions[i].x+dx}px`;t.style.top=`${dragState.positions[i].y+dy}px`});renderConnections()}
  if(boxState){const p=canvasPoint(e),x=Math.min(p.x,boxState.start.x),y=Math.min(p.y,boxState.start.y),w=Math.abs(p.x-boxState.start.x),h=Math.abs(p.y-boxState.start.y);Object.assign($('#selectionBox').style,{left:`${x}px`,top:`${y}px`,width:`${w}px`,height:`${h}px`});if(boxState.ai){const badge=$('#aiSelectionBadge');badge.style.left=`${x}px`;badge.style.top=`${y-34}px`}}}
function pointerUp(){if(boxState){const b=$('#selectionBox').getBoundingClientRect(),large=b.width>4||b.height>4;$$('.object').filter(el=>!el.classList.contains('ai-suggestion-layer')).forEach(el=>{const r=el.getBoundingClientRect();if(large&&r.left<b.right&&r.right>b.left&&r.top<b.bottom&&r.bottom>b.top)select(el,true)});$('#selectionBox').style.display='none';$('#aiSelectionBadge').classList.add('hidden');if(selected.size){updateSelectionBar();logActivity('Marquee selection',`${selected.size} canvas object${selected.size===1?'':'s'} selected`)}else clearSelection()}if(dragState){logActivity('Notes moved',`${dragState.targets.length} selected object${dragState.targets.length===1?'':'s'} moved`);updateSelectionBar()}panState=dragState=boxState=null;canvas.classList.remove('panning')}

function voteClick(e){e.stopPropagation();voteElement(e.currentTarget.closest('.object'))}
function voteElement(el){const b=el.querySelector('.note-vote');if(!b){notify('Voting works on notes');return}const n=Number(b.querySelector('b').textContent);b.classList.toggle('voted');b.querySelector('b').textContent=b.classList.contains('voted')?n+1:Math.max(0,n-1);b.firstChild.textContent=b.classList.contains('voted')?'♥ ':'♡ ';notify(b.classList.contains('voted')?'Vote added':'Vote removed')}
function createComment(x,y){saveHistory();const el=document.createElement('div');el.className='comment-pin object created';el.dataset.id=`o${idSeed++}`;el.dataset.type='comment';el.style.left=`${x}px`;el.style.top=`${y}px`;el.innerHTML='<span>1</span><div class="comment-popover"><strong>You</strong><p contenteditable="true">Add a thoughtful comment...</p><button>Reply</button></div>';canvas.append(el);bindObject(el);el.classList.add('open');el.querySelector('p').focus();notify('Comment added')}
function addComment(target){const x=(parseFloat(target.style.left)||0)+target.offsetWidth-8,y=parseFloat(target.style.top)||0;createComment(x,y)}
function handleConnect(el){if(!connectStart){connectStart=el;el.classList.add('connect-source');notify('Now choose a second item')}else if(connectStart!==el){saveHistory();connections.push([connectStart.dataset.id,el.dataset.id]);connectStart.classList.remove('connect-source');connectStart=null;renderConnections();notify('Connection created')}}
const connections=[];
function renderConnections(){connectionLayer.innerHTML='';connections.forEach(([a,b])=>{const A=$(`[data-id="${a}"]`),B=$(`[data-id="${b}"]`);if(!A||!B)return;const x1=(parseFloat(A.style.left)||0)+A.offsetWidth/2,y1=(parseFloat(A.style.top)||0)+A.offsetHeight/2,x2=(parseFloat(B.style.left)||0)+B.offsetWidth/2,y2=(parseFloat(B.style.top)||0)+B.offsetHeight/2;const path=document.createElementNS('http://www.w3.org/2000/svg','path');const bend=Math.max(50,Math.abs(x2-x1)*.35);path.setAttribute('d',`M ${x1} ${y1} C ${x1+bend} ${y1}, ${x2-bend} ${y2}, ${x2} ${y2}`);path.setAttribute('class','connection-path');connectionLayer.append(path)})}

function setTool(btn){$$('.tool').forEach(b=>b.classList.remove('active'));btn.classList.add('active');tool=btn.dataset.tool;if(connectStart){connectStart.classList.remove('connect-source');connectStart=null}wrap.dataset.tool=tool;notify(`${btn.title}`)}
function listHtml(items){return Array.isArray(items)&&items.length?`<ul>${items.map(x=>`<li>${escapeHtml(String(x))}</li>`).join('')}</ul>`:'<p>没有从所选内容中发现明确证据。</p>'}
async function analyse(mode='organise'){if(selected.size<1){notify('Use Select to draw around the notes first');return}workspace.classList.remove('ai-closed');$('#aiPanel').classList.remove('closed');$$('.ai-content').forEach(p=>p.classList.add('hidden'));$('#analysisView').classList.remove('hidden');$('#analysisCount').textContent=selected.size;$('#analysisLoading').classList.remove('hidden');$('#analysisLoading p').textContent='DeepSeek 正在阅读所选内容…';$('#analysisResults').classList.add('hidden');pendingAiSelection=[...selected];const selectedTexts=pendingAiSelection.map(id=>$(`[data-id="${id}"]`)?.innerText?.trim()).filter(Boolean);logActivity('AI analysis request',`${mode==='summary'?'Summary':'Reflection'} requested for ${selected.size} selected objects`);try{const response=await fetch('/api/analyse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task:mode,notes:selectedTexts})});const payload=await response.json();if(!response.ok)throw Object.assign(new Error(payload.error||'AI request failed'),{code:payload.code});const a=payload.analysis||{};const result=`<section><span>DeepSeek reflection · ${escapeHtml(payload.model||'model')}</span><p>${escapeHtml(String(a.summary||'暂无总结'))}</p></section><section><span>可能的主题</span>${listHtml(a.themes)}</section><section><span>不同视角 / 潜在冲突</span>${listHtml(a.perspectives)}</section><section><span>帮助团队讨论的问题</span>${listHtml(a.questions)}</section><section><span>可选的下一步</span>${listHtml(a.next_actions)}</section><div class="analysis-note">这是基于人类所选内容的建议，不是决定。原始画布没有被移动或修改。你今天还可使用 ${payload.remaining_for_user??'—'} 次。</div><div class="analysis-actions"><button data-ai-action="discuss">Discuss</button><button data-ai-action="cancel">Close</button></div>`;$('#analysisResults').innerHTML=result;notify('DeepSeek reflection ready')}catch(err){if(err.code==='unauthorized')showAccessGate();const evidence=selectedTexts.slice(0,6).map(text=>`<li>${escapeHtml(text.replace(/\s+/g,' ').slice(0,180))}</li>`).join('');$('#analysisResults').innerHTML=`<section><span>请求未完成</span><p>${escapeHtml(err.message||'模型请求失败')}</p></section><section><span>你实际选择的内容</span><ul>${evidence||'<li>没有可读取的文字。</li>'}</ul></section><div class="analysis-note">这里不会伪造 AI 结论，也不会移动原始画布。</div><div class="analysis-actions"><button data-ai-action="cancel">Close</button></div>`}finally{$('#analysisLoading').classList.add('hidden');$('#analysisResults').classList.remove('hidden');bindAiActions($('#analysisResults'))}}
function createSuggestionLayer(chosen){saveHistory();$('.ai-suggestion-layer')?.remove();const right=Math.max(...chosen.map(el=>(parseFloat(el.style.left)||0)+el.offsetWidth))+90,top=Math.min(...chosen.map(el=>parseFloat(el.style.top)||0)),refs=chosen.map(el=>`#${el.dataset.id}`).join(', ');const layer=document.createElement('section');layer.className='object ai-suggestion-layer created';layer.dataset.id=`o${idSeed++}`;layer.dataset.type='ai-insight';layer.style.left=`${right}px`;layer.style.top=`${top}px`;layer.innerHTML=`<header><span class="ai-face tiny"><i></i><b></b></span><div><strong>Applied organisation copy</strong><small>Original notes remain unchanged</small></div></header><div class="suggested-theme mustard"><b>01</b><span>Scattered knowledge</span></div><div class="suggested-theme coral"><b>02</b><span>Different interpretations</span></div><div class="suggested-theme mint"><b>03</b><span>Unclear next action</span></div><article><strong>Repeated ideas</strong><p>Direction and follow-through may be repeated concerns.</p><small>Source notes: ${refs}</small></article><article><strong>Insight</strong><p>Content feedback and collaboration feedback may need separate discussion.</p><small>Linked to the selected source notes</small></article><div class="canvas-ai-actions"><button data-layer-action="edit">Edit</button><button data-layer-action="discuss">Discuss</button><button data-layer-action="reject">Remove copy</button></div>`;canvas.append(layer);bindObject(layer);logActivity('Accepted suggestion',`Organisation copy created from ${chosen.length} source objects`);$$('[data-layer-action]',layer).forEach(btn=>btn.onclick=e=>{e.stopPropagation();const action=btn.dataset.layerAction;if(action==='reject'){saveHistory();layer.remove();logActivity('Rejected suggestion','Applied organisation copy removed');notify('Copy removed. Original notes remain')}else if(action==='edit'){layer.querySelectorAll('span,p').forEach(x=>x.contentEditable='true');notify('Applied copy is editable')}else{switchTab('chat');addHuman('Let’s compare the applied themes with the source notes.')}})}
function bindAiActions(root=document){$$('[data-ai-action]',root).forEach(btn=>btn.onclick=()=>{const a=btn.dataset.aiAction;if(a==='apply'){const chosen=pendingAiSelection.map(id=>$(`[data-id="${id}"]`)).filter(Boolean);if(chosen.length)createSuggestionLayer(chosen);switchTab('insights');notify('Organisation copy applied beside the originals')}if(a==='cancel'){logActivity('Rejected suggestion','AI organisation preview cancelled');switchTab('insights');notify('Preview cancelled. Canvas unchanged')}if(a==='discuss'){switchTab('chat');addHuman('Let’s discuss this organisation preview before applying it.')}if(a==='edit'){$$('.theme-chips button',root).forEach(x=>x.contentEditable='true');$('.theme-chips button',root)?.focus();notify('Category names are editable')}if(a==='why'){switchTab('chat');addAi('I suggested these categories because the selected notes repeat concerns about scattered information, different interpretations, and unclear follow-through. Does that match the team’s reading?')}})}
function switchTab(name){$$('.ai-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['insights','chat','progress','activity'].forEach(n=>$(`#${n}Panel`).classList.toggle('hidden',n!==name));$('#analysisView').classList.add('hidden')}
function addHuman(text){const el=document.createElement('div');el.className='human-message';el.innerHTML=`<p>${escapeHtml(text)}</p><time>You · now</time>`;$('#chatPanel').append(el);$('#chatPanel').scrollTop=$('#chatPanel').scrollHeight}
function addAi(text){const el=document.createElement('div');el.className='ai-message';el.innerHTML=`<span class="ai-face tiny"><i></i><b></b></span><div><p>${text}</p><time>Now</time></div>`;$('#chatPanel').append(el);$('#chatPanel').scrollTop=$('#chatPanel').scrollHeight}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function showAccessGate(){if($('#accessGate'))return;const gate=document.createElement('div');gate.id='accessGate';gate.className='access-gate';gate.innerHTML=`<form class="access-card"><span class="ai-face"><i></i><b></b></span><small>PRIVATE TEAM PREVIEW</small><h2>进入 CoLab Canvas</h2><p>请输入团队访问码。访问码用于保护共享的 AI 使用额度。</p><label>访问码<input id="accessCode" type="password" autocomplete="current-password" required></label><button type="submit">进入工作区</button><div class="access-error" role="alert"></div><em>AI 只分析你主动选择的画布内容。</em></form>`;document.body.append(gate);gate.querySelector('input').focus();gate.querySelector('form').onsubmit=async e=>{e.preventDefault();const error=gate.querySelector('.access-error'),button=gate.querySelector('button');button.disabled=true;button.textContent='正在验证…';error.textContent='';try{const response=await fetch('/api/unlock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:gate.querySelector('input').value})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'验证失败');gate.remove();notify('欢迎进入 CoLab Canvas')}catch(err){error.textContent=err.message;button.disabled=false;button.textContent='进入工作区'}}}
async function initAccessGate(){try{const response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)return;const status=await response.json();if(status.auth_required&&!status.authenticated)showAccessGate()}catch(err){/* Static GitHub Pages preview has no backend. */}}

$$('.object').forEach(bindObject);$$('.tool[data-tool]').forEach(btn=>btn.onclick=()=>setTool(btn));$('[data-tool="ai"]').onclick=()=>analyse('organise');canvas.addEventListener('pointerdown',canvasDown);window.addEventListener('pointermove',pointerMove);window.addEventListener('pointerup',pointerUp);
wrap.addEventListener('wheel',e=>{e.preventDefault();const before=canvasPoint(e);const factor=e.deltaY<0?1.08:.92;zoom=Math.max(.35,Math.min(1.8,zoom*factor));const r=wrap.getBoundingClientRect();panX=e.clientX-r.left-before.x*zoom;panY=e.clientY-r.top-before.y*zoom;transform()},{passive:false});
$('#zoomIn').onclick=()=>{zoom=Math.min(1.8,zoom+.1);transform()};$('#zoomOut').onclick=()=>{zoom=Math.max(.35,zoom-.1);transform()};$('#fitCanvas').onclick=()=>{zoom=.72;panX=10;panY=0;transform()};$('#clearSelection').onclick=clearSelection;$('#analyseBtn').onclick=analyse;
$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;
function deleteSelected(){if(!selected.size)return;saveHistory();const count=selected.size;[...selected].forEach(id=>$(`[data-id="${id}"]`)?.remove());connections.splice(0,connections.length,...connections.filter(([a,b])=>!selected.has(a)&&!selected.has(b)));clearSelection();renderConnections();logActivity('Notes deleted',`${count} selected object${count===1?'':'s'} deleted`);notify('Selection deleted')}
$('#deleteSelectionBtn').onclick=deleteSelected;$('#summariseSelectionBtn').onclick=()=>analyse('summary');$('#moveBtn').onclick=()=>notify('Drag any selected note to move the full selection');
$('#duplicateBtn').onclick=()=>{const count=selected.size;[...selected].forEach(id=>{const src=$(`[data-id="${id}"]`);if(src?.dataset.type==='sticky')createObject('sticky',(parseFloat(src.style.left)||0)+30,(parseFloat(src.style.top)||0)+30,{color:[...src.classList].find(c=>['yellow','green','blue','coral'].includes(c))})});logActivity('Notes created',`${count} selected object${count===1?'':'s'} duplicated`);notify('Selection duplicated')};
$('#groupBtn').onclick=()=>{logActivity('Notes grouped',`${selected.size} selected objects grouped for movement`);notify('Selection grouped for movement')};
$('#imageInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{createObject('image',(pendingImagePoint?.x||400)-110,(pendingImagePoint?.y||300)-80,{src:reader.result});notify('Image added to canvas')};reader.readAsDataURL(file);e.target.value=''};
$$('.note-vote').forEach(b=>b.onclick=voteClick);
$$('.ai-tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));bindAiActions();
$('#aiToggle').onclick=()=>{workspace.classList.toggle('ai-closed');$('#aiPanel').classList.toggle('closed')};$('#closeAI').onclick=()=>{workspace.classList.add('ai-closed');$('#aiPanel').classList.add('closed')};
$('#closeAnalysis').onclick=()=>switchTab('insights');
$('#aiForm').onsubmit=async e=>{e.preventDefault();const input=$('#aiPrompt'),value=input.value.trim();if(!value)return;const context=[...selected].map(id=>$(`[data-id="${id}"]`)?.innerText?.trim()).filter(Boolean);switchTab('chat');addHuman(value);input.value='';addAi('正在阅读你主动选择的内容…');const pending=$('#chatPanel .ai-message:last-child');try{const response=await fetch('/api/analyse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task:`回答团队问题：${value}`,notes:context.length?context:[value]})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'AI request failed');const a=payload.analysis||{};pending?.remove();addAi(`${escapeHtml(String(a.summary||''))}<br><br><strong>可以一起讨论：</strong><br>${(a.questions||[]).map(x=>`• ${escapeHtml(String(x))}`).join('<br>')}`)}catch(err){pending?.remove();addAi('模型还没有连接成功。请确认使用 server.py 启动，并在启动前设置 DEEPSEEK_API_KEY。')}};
$$('.quick-ai').forEach(btn=>btn.onclick=()=>{const label=btn.dataset.quick;if(label==='Summarise'){if(selected.size)analyse();else notify('Select the content you want summarised')}else{switchTab('chat');addAi('What is the team trying to decide next? Select the relevant notes so I can respond with context.')}});
$$('[data-prompt]').forEach(b=>b.onclick=()=>{$('#aiPrompt').value=b.dataset.prompt;$('#aiPrompt').focus()});
$('#attachBtn').onclick=()=>{pendingImagePoint={x:1040,y:690};$('#imageInput').click()};
let recording=false,mediaRecorder=null,recordedChunks=[],recordingStream=null;
function addVoiceNote(blob){const url=URL.createObjectURL(blob),el=document.createElement('div');el.className='voice-note';el.innerHTML=`<div><strong>Team voice note</strong><small>Saved in this browser session · ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div><audio controls src="${url}"></audio><a download="team-voice-note-${Date.now()}.webm" href="${url}">Download</a>`;$('#chatPanel').append(el);switchTab('chat');$('#chatPanel').scrollTop=$('#chatPanel').scrollHeight;logActivity('Voice note recorded','Audio is available for playback and download in Discussion')}
async function voice(){if(recording&&mediaRecorder){mediaRecorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){notify('This browser does not support audio recording');return}try{recordingStream=await navigator.mediaDevices.getUserMedia({audio:true});recordedChunks=[];mediaRecorder=new MediaRecorder(recordingStream);mediaRecorder.ondataavailable=e=>{if(e.data.size)recordedChunks.push(e.data)};mediaRecorder.onstop=()=>{const blob=new Blob(recordedChunks,{type:mediaRecorder.mimeType||'audio/webm'});recordingStream?.getTracks().forEach(track=>track.stop());recordingStream=null;recording=false;$('#voiceBtn').classList.remove('recording');$('#voiceFab').classList.remove('recording');$('#voiceBtn span')?.replaceChildren('Voice');addVoiceNote(blob);notify('Recording saved in Discussion')};mediaRecorder.start();recording=true;$('#voiceBtn').classList.add('recording');$('#voiceFab').classList.add('recording');$('#voiceBtn span')?.replaceChildren('Stop');notify('Recording… click again to stop')}catch(err){recording=false;notify(err?.name==='NotAllowedError'?'Microphone permission was not granted':'Could not start microphone recording')}}
$('#voiceBtn').onclick=voice;$('#voiceFab').onclick=voice;
$('#projectSwitcher').onclick=$('#homeBtn').onclick=()=>$('#projectDialog').showModal();$('.dialog-close').onclick=()=>$('#projectDialog').close();$('#newProjectBtn').onclick=()=>{saveHistory();$$('.object').forEach(el=>el.remove());connections.splice(0);renderConnections();clearSelection();$('#projectDialog').close();notify('Blank page created. Build your own structure')};
$$('.stage').forEach(s=>s.onclick=()=>{$$('.stage').forEach(x=>x.classList.remove('active'));s.classList.add('active');notify(`${s.dataset.stage} stage selected`)});$('#shareBtn').onclick=()=>{navigator.clipboard?.writeText(location.href);notify('Workspace link copied')};
window.addEventListener('keydown',e=>{const meta=e.metaKey||e.ctrlKey,typing=e.target.closest?.('[contenteditable],textarea,input');if(meta&&(e.key.toLowerCase()==='z'||e.code==='KeyZ')){if(typing&&document.activeElement===typing)return;e.preventDefault();e.shiftKey?redo():undo();return}if(typing)return;if(e.code==='Space'){spaceDown=true;e.preventDefault();wrap.classList.add('space-pan');return}if(e.key==='Escape'){if(boxState){boxState=null;$('#selectionBox').style.display='none';$('#aiSelectionBadge').classList.add('hidden')}else clearSelection();notify('Selection cancelled');return}if(meta&&e.key.toLowerCase()==='c'){clipboard=[...selected].map(id=>$(`[data-id="${id}"]`)?.outerHTML).filter(Boolean);notify(`${clipboard.length} item${clipboard.length===1?'':'s'} copied`);return}if(meta&&e.key.toLowerCase()==='v'){if(!clipboard.length)return;e.preventDefault();saveHistory();clearSelection();clipboard.forEach(html=>{const holder=document.createElement('div');holder.innerHTML=html;const el=holder.firstElementChild;el.dataset.id=`o${idSeed++}`;el.style.left=`${(parseFloat(el.style.left)||0)+36}px`;el.style.top=`${(parseFloat(el.style.top)||0)+36}px`;canvas.append(el);bindObject(el);select(el,true)});logActivity('Notes created',`${clipboard.length} copied objects pasted`);notify('Pasted');return}if((e.key==='Delete'||e.key==='Backspace')&&selected.size)deleteSelected();if(meta&&e.key.toLowerCase()==='d'&&selected.size){e.preventDefault();$('#duplicateBtn').click()}},{capture:true});window.addEventListener('keyup',e=>{if(e.code==='Space'){spaceDown=false;wrap.classList.remove('space-pan')}});
transform();renderConnections();updateHistoryButtons();renderActivity();logActivity('Page opened','Research demo page ready');initAccessGate();
